"""empty message

Revision ID: 13dbf703736f
Revises: 5c09a309a338
Create Date: 2020-12-11 18:33:17.520504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13dbf703736f'
down_revision = '5c09a309a338'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz', sa.Column('creation_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz', 'creation_date')
    # ### end Alembic commands ###
