"""empty message

Revision ID: 61655bc3c0bd
Revises: 
Create Date: 2019-12-14 17:14:09.305266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61655bc3c0bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz',
    sa.Column('id_', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_')
    )
    op.create_table('guess',
    sa.Column('id_', sa.BigInteger(), nullable=False),
    sa.Column('quiz_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id_'], ),
    sa.PrimaryKeyConstraint('id_')
    )
    op.create_table('question',
    sa.Column('id_', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=True),
    sa.Column('text_long', sa.String(length=255), nullable=True),
    sa.Column('quiz_id', sa.BigInteger(), nullable=True),
    sa.Column('index', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id_'], ),
    sa.PrimaryKeyConstraint('id_')
    )
    op.create_table('answer',
    sa.Column('id_', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=True),
    sa.Column('question_id', sa.BigInteger(), nullable=True),
    sa.Column('correct_answer', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id_'], ),
    sa.PrimaryKeyConstraint('id_')
    )
    op.create_table('answer_guess',
    sa.Column('id_', sa.BigInteger(), nullable=False),
    sa.Column('guess_id', sa.BigInteger(), nullable=True),
    sa.Column('answer_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['answer_id'], ['answer.id_'], ),
    sa.ForeignKeyConstraint(['guess_id'], ['guess.id_'], ),
    sa.PrimaryKeyConstraint('id_')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer_guess')
    op.drop_table('answer')
    op.drop_table('question')
    op.drop_table('guess')
    op.drop_table('quiz')
    # ### end Alembic commands ###
