"""index column for question

Revision ID: a326ccd87a4b
Revises: 3fb6f4290e00
Create Date: 2019-12-05 18:48:20.430755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a326ccd87a4b'
down_revision = '3fb6f4290e00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('index', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'index')
    # ### end Alembic commands ###
