"""empty message

Revision ID: ac8d8cb4fe87
Revises: a326ccd87a4b
Create Date: 2019-12-07 23:09:07.696413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac8d8cb4fe87'
down_revision = 'a326ccd87a4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('text_long', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'text_long')
    # ### end Alembic commands ###
