"""empty message

Revision ID: f48c1faa6bd9
Revises: 
Create Date: 2019-11-29 20:53:43.065738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f48c1faa6bd9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz',
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('correct_answers', sa.String(length=10), nullable=True),
    sa.Column('id_', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_')
    )
    op.create_table('answer',
    sa.Column('id_', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('answers', sa.String(length=10), nullable=True),
    sa.Column('quiz_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id_'], ),
    sa.PrimaryKeyConstraint('id_')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer')
    op.drop_table('quiz')
    # ### end Alembic commands ###
